// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DecryptionDatum struct {
	Eon              int64
	IdentityPreimage []byte
	DecryptionKey    []byte
	Slot             int64
	BlockHash        []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type DecryptionKeyShare struct {
	Eon                int64
	IdentityPreimage   []byte
	KeyperIndex        int64
	DecryptionKeyShare []byte
	Slot               int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type EncryptedTx struct {
	TxIndex          int64
	Eon              int64
	Tx               []byte
	IdentityPreimage []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
